# ~/.bashrc
# colors
# to check all colors:
# for i in {0..255}; do echo -e "\e[38;5;${i}mColor ${i}\e[0m"; done
light_grey="$(tput bold; tput setaf 7)" # red 160 # grey-white 7 # white 15
white="$(tput bold; tput setaf 15)"
dark_red="$(tput bold; tput setaf 160)"
nc="$(tput sgr0)"
green="$(tput bold; tput setaf 2)"

# If not running interactively, don't do anything
[[ $- != *i* ]] && return

[[ ":$PATH:" != *":$HOME/go/bin:"* ]] && export PATH="$PATH:$HOME/go/bin"
[[ ":$PATH:" != *":$HOME/.local/bin:"* ]] && export PATH="$PATH:$HOME/.local/bin"
[[ ":$PATH:" != *":$HOME/.local/share/gem/ruby/3.4.0/bin:"* ]] && export PATH="$PATH:$HOME/.local/share/gem/ruby/3.4.0/bin"

if [[ -n "$SSH_CONNECTION" ]]; then
    #PS1='\[\e[0;32m\]\u@\h:\w\$ \[\e[0m\]'
    PS1="\[\e[$green\][ \u@\h \[$light_grey\]\w\[$light_grey\] \[$green\]]\$ \[\e[0m\]"
else
    PS1="\[$dark_red\][ \[$light_grey\]\u@**** \[$light_grey\]\w\[$light_grey\] \[$dark_red\]]\\[$light_grey\]$ \[$nc\]"
fi

use() {
  if [ -n "$1" ]; then
    tmux -u new-session -s "$1"
  else
    if [ -n "$TMUX" ]; then
      tmux -u choose-tree -s
    else
      if tmux ls >/dev/null 2>&1; then
        tmux -u attach \; choose-tree -s
      else
        tmux -u
      fi
    fi
  fi
}

pac() {
    local sub="$1"
    shift || { echo "usage: pac {add|del|find|new/update} ..."; return 1; }

    case "$sub" in
        add)
            for arg in "$@"; do
                [[ "$arg" == -S* ]] && exec doas apt "$@"
            done
            doas apt install "$@"
            ;;

        del|remove)
            for arg in "$@"; do
                [[ "$arg" == -R* ]] && exec doas apt "$@"
            done
            doas apt remove "$@"
            ;;

        new|update)
            doas apt update && doas apt upgrade 
            ;;

        find|search)
            for arg in "$@"; do
                [[ "$arg" == -S* ]] && exec doas apt "$@"
            done
            doas apt search "$@"
            ;;

        *)
            echo "usage:"
            echo "  pac add  <pkg> [flags]"
            echo "  pac del  <pkg> [flags]"
            echo "  pac find <query> [flags]"
            echo "  pac new"
            return 1
            ;;
    esac
}

alias sudo='doas'
alias cb='xclip -selection clipboard -i $@'
alias vim=nvim
alias vi=vim
alias svim='doas nvim'
alias ll='ls -lah --color=auto'
alias ls='ls --color=auto'
alias sl='ls'
alias grep='grep --color=auto'
alias diff='diff --color=auto'

alias fix='stty raw -echo;fg'
alias ad='cd ~/tools/ad'
alias lin='cd ~/tools/lin'
alias web='cd ~/tools/web'
alias cman='/usr/bin/man'
alias man='man 2'

eval "$(direnv hook bash)"

#export NVM_DIR="$HOME/.nvm"
#[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
#[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion
