#!/usr/bin/env bash

# virtualbox
vbox=$(dmesg |grep -io virtualbox)
if [ ! -z "$vbox" ]
then
  /usr/bin/VBoxClient --checkhostversion
  /usr/bin/VBoxClient --seamless
  /usr/bin/VBoxClient --clipboard
  /usr/bin/VBoxClient --vmsvga
fi

export QT_QPA_PLATFORMTHEME=qt6ct

#exec tint2 &

# wallpaper
# exec feh --bg-scale /usr/share/blackarch/wallpaper.jpg &

